import { expect, test } from "@playwright/test";
import {
  expectNoConsoleErrors,
  expectStableChrome,
  primeLens,
  watchConsole,
} from "./helpers";
/**
 * THE TWO PAGES THAT GOT SHORTER, and the two things that must not have got smaller
 * with them.
 *
 * `/deals` measured 17,499px at 390px and `/ledger` 10,047px - five times this app's
 * own median page - because the index printed every deal as full two-sided prose (so
 * every deal twice, mirrored) and the ledger opened all twenty-nine of its textareas
 * at once. Both are now a list of shut summary rows.
 *
 * A collapse and a deletion look identical in a screenshot, and identical in a height
 * measurement, which is exactly why the height is not what these tests assert. They
 * assert the COUNT and the REACHABILITY: every deal still has its own row and its own
 * receipt, and every ledger entry still opens into the same editor it always had.
 */
test("the deal index still surfaces every deal, one row each, each one its own receipt", async ({
  page,
}) => {
  const guard = watchConsole(page);
  await primeLens(page);
  await page.goto("/deals");
  // networkidle, not the default "load": this test clicks a <Link> further down,
  // and `expectStableChrome`'s check only proves the SSR'd HTML rendered, not that
  // React has hydrated. Reproduced directly (5 attempts, console/pageerror both
  // watched): clicking right after "load" landed inside that gap and silently did
  // nothing - no error, no navigation - on a *fast* dev server; the same click
  // always worked once the page had a moment to settle, and always worked on the
  // slower pre-conversion build where that gap happened to be masked by per-request
  // compile time. Waiting for the network to go idle here is the fix that turned a
  // repeatable failure into a reliable pass.
  await page.waitForLoadState("networkidle");
  await expectStableChrome(page);
  // The page's own headline figure, read off the page rather than hard-coded: the
  // fixture corpus is regenerated by lib/providers/fixture/generate.ts and a number
  // pinned here would only ever pin this test to a stale corpus. What matters is that
  // the two agree - a row for every deal the page claims to hold.
  const claimed = Number(
    (
      await page
        .getByText("Deals on record", { exact: true })
        .locator("xpath=following-sibling::div[1]")
        .innerText()
    ).replace(/[^0-9]/g, ""),
  );
  expect(claimed).toBeGreaterThan(0);
  const rows = page.getByTestId("deal-index").locator("> li");
  await expect(rows).toHaveCount(claimed);
  // Every row is a link INTO the receipt, which is now the only place the deal's
  // prose exists. A row that lost its href would be a deal nobody can read any more.
  const hrefs = await page
    .getByTestId("deal-index")
    .locator("> li > a")
    .evaluateAll((els) => els.map((e) => e.getAttribute("href")));
  expect(hrefs).toHaveLength(claimed);
  expect(hrefs.every((h) => h?.startsWith("/deals/"))).toBe(true);
  expect(new Set(hrefs).size).toBe(claimed);
  // And one of them really lands on a receipt, with the receipt's own heading.
  await rows.first().locator("a").click();
  await expect(page).toHaveURL(/\/deals\/.+/);
  await expect(
    page.getByRole("heading", { name: /what each side is worth today/i }),
  ).toBeVisible();
  expectNoConsoleErrors(guard);
});
test("the ledger pins the newest uncaptured decision and folds the rest", async ({
  page,
}) => {
  const guard = watchConsole(page);
  await primeLens(page);
  await page.goto("/ledger");
  await expectStableChrome(page);
  // ONE editor open on arrival, and it is the pinned card. This is the whole point of
  // the redesign: the Desk badge promises a single next action, and the page used to
  // answer with an open textarea per notable decision.
  await expect(
    page.getByRole("heading", { name: "Newest to capture" }),
  ).toBeVisible();
  const visibleBoxes = page.getByRole("textbox");
  const visibleCount = await visibleBoxes.evaluateAll(
    (els) => els.filter((e) => e.offsetParent !== null).length,
  );
  expect(visibleCount).toBe(1);
  // The pinned one is genuinely the NEWEST uncaptured decision, not merely the first
  // thing in the array. Both lists run newest-first, so the pinned card's (season,
  // week) must be at least the top folded row's - if the pin ever picked the oldest,
  // or picked from an unsorted array, this is where it shows up.
  const stamp = (text) => {
    const m = text.match(/(\d{4})\s*·\s*wk\s*(\d+)/i);
    if (!m) throw new Error(`no season/week stamp in: ${text}`);
    return [Number(m[1]), Number(m[2])];
  };
  const pinned = stamp(await page.getByTestId("ledger-pinned").innerText());
  const rows = page.getByTestId("ledger-rows").first().locator("> li");
  const first = stamp(await rows.first().innerText());
  expect(pinned[0] * 100 + pinned[1]).toBeGreaterThanOrEqual(
    first[0] * 100 + first[1],
  );
  // Nothing was dropped to get short: every folded row still opens into the same
  // editor, one tap, no navigation.
  const target = rows.first();
  await expect(target.locator("details")).not.toHaveAttribute("open", /.*/);
  await target.locator("summary").click();
  await expect(target.getByRole("textbox")).toBeVisible();
  await expect(target.getByRole("button", { name: "Save" })).toBeVisible();
  expectNoConsoleErrors(guard);
});
